[package]
name = "route_codegen"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.104", features = ["parsing", "visit", "full"] }
quote = "1.0.40"
proc-macro2 = "1.0.95"
once_cell = "1.21.3"
