[package]
name = "untitled"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
env_logger = "0.11.8"
route_macro = { path = "route_macro" } # 正确路径 ✅

[workspace]
members = ["route_codegen",
    "route_macro", # 正确路径 ✅
]

[dependencies.route_codegen]
path = "route_codegen"
