[package]
name = "web_demo"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
env_logger = "0.11.8"
log = "0.4.27"
[workspace]
members = ["api_tool", "route_codegen"]

[dependencies.route_codegen]
path = "route_codegen"
[dependencies.api_tool]
path = "api_tool"
