services:
  web_demo:
    image: web_demo:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080"
    environment:
      RUST_LOG: "web_demo=info,actix_web=info"
    networks:
      web_demo_network:

networks:
  web_demo_network: