services:
  web_demo:
    image: web_demo:latest
    ports:
      - "8980:8080"
    environment:
      RUST_LOG: "web_demo=info,actix_web=info"
    #    healthcheck:
    #      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
    #      interval: 5s
    #      timeout: 2s
    #      retries: 3
    restart: unless-stopped
